### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by niklaslong**
Obviates #1569 and #1568.

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
A red lockfile diff, nice :ok_hand:.

**Comment by niklaslong** [comment]
Updated to include new updates, obviates #1579, #1581, #1582.

**Comment by niklaslong** [comment]
Updated and obviates #1584, #1585, #1587, #1591, #1592

**Comment by niklaslong** [comment]
Also contains #1588.

**Review by howardwu — APPROVED** [review]

**Pull request merged**
