### PR TITLE
Move from structopt to clap

### LINKED ISSUE #1675: Switch from structopt to clap
As [`structopt` docs state themselves](https://github.com/TeXitoi/structopt#maintenance), that crate is now in maintenance mode, as its features are now available in `clap`, which is actively maintained and is itself one of `structopt`'s dependencies.

### PR DESCRIPTION
**Pull request by ljedrz**
The reasoning is provided in the linked issue.

note: the address parameter for the crawler changes from `node` to `addr` in order not to mix it up with the proper node.

Closes https://github.com/AleoHQ/snarkOS/issues/1675.

### CODE REVIEW

**Comment by ljedrz** [comment]
Rebased.

**Review by niklaslong — APPROVED** [review]
LGTM 👍

**Comment by ljedrz** [comment]
Happy to rebase when greenlit by @howardwu.

**Review by howardwu — APPROVED** [review]

**Comment by ljedrz** [comment]
2CA strikes again:
```
failures:

---- helpers::block_requests::tests::test_block_requests_case_2ca stdout ----
thread 'helpers::block_requests::tests::test_block_requests_case_2ca' panicked at 'cannot sample empty range', /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.8.5/src/rng.rs:134:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    helpers::block_requests::tests::test_block_requests_case_2ca
```

Cc https://github.com/AleoHQ/snarkOS/issues/1634

**Pull request merged**
