### PR TITLE
Canary v0.4.2 release

### PR DESCRIPTION
**Pull request by zkxuerb**
## Motivation

Please see below for improvements included in this release:
[Fix] Add subdag verification checks
[Fix] Make deployment verification consistent by deterministically seeding the RNG.

## Related PRs
https://github.com/AleoNet/snarkVM/pull/2537
https://github.com/AleoNet/snarkVM/pull/2535

### CODE REVIEW

**Review by snarkworld — DISMISSED** [review]
LGTM

**Comment by raychu86** [comment]
LGTM after `Message` and `Event` version bumps.

**Review by evanmarshall — DISMISSED** [review]

**Review by raychu86 — DISMISSED** [review]
LGTM

**Review by snarkworld — APPROVED** [review]
LGTM

**Review by raychu86 — APPROVED** [review]

**Pull request merged**
