### PR TITLE
Dependency update roll-up

### PR DESCRIPTION
**Pull request by ljedrz**
This is a roll-up containing all pending dependency updates.

### CODE REVIEW

**Review by howardwu — APPROVED** [review]
LGTM

**Comment by howardwu** [comment]
@ljedrz can you resolve the Cargo lock file?

**Comment by ljedrz** [comment]
Done; note that I changed the snarkVM dependency from a commit SHA to strict `=0.10.2` (this release happened right after that commit).

**Review by howardwu — APPROVED** [review]
LGTM

**Pull request merged**
