### PR TITLE
Fix CI failures

### PR DESCRIPTION
**Pull request by ljedrz**
This PR comments out some test features that are currently unused and a few old tests that need to be fixed first.

### CODE REVIEW

**Comment by ljedrz** [comment]
While I'm not exactly sure why the CI reports a dependency issue in the `environment` and `snarkos` jobs (as I can't reproduce it locally), we currently don't have any tests there, so we can disable them for the time being.

**Comment by raychu86** [comment]
Can you help fix them instead of leaving them commented out?

For example, the rocksdb tests can be updated to address the breaking changes.

**Comment by ljedrz** [comment]
This was an initial proposal to quickly unblock other work that kept getting bogus failures, it might still be a good idea until the failures are fixed; as for rocksdb, this is already in progress as https://github.com/AleoHQ/snarkOS/pull/1878.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable.

**Pull request closed without merging**
