### PR TITLE
Fix lints from the updated nightly

### PR DESCRIPTION
**Pull request by ljedrz**
It seems that the nightly image was updated, causing the pending PRs to fail the `clippy` job. This PR takes care of the current clippy lints.

### CODE REVIEW

**Comment by ljedrz** [comment]
Oof, seems that my nightly was just 2 days shy of one new lint; checking it out now.

**Comment by ljedrz** [comment]
I'm not 100% sure the new `format_args` vs. `await` error is legitimate, but I haven't found any related bug reports, and working around it is trivial and doesn't have downsides.

**Review by niklaslong — APPROVED** [review]
LGTM 👍

**Review by jules — APPROVED** [review]

**Review by raychu86 — APPROVED** [review]

**Comment by ljedrz** [comment]
This appears to be a bug after all: https://github.com/rust-lang/rust/issues/93274. That being said, the workaround doesn't hurt.

**Review by howardwu — APPROVED** [review]

**Pull request merged**
