### PR TITLE
Feat: inbound message count metrics

### PR DESCRIPTION
**Pull request by niklaslong**
Introduces a metric to count each message type. Builds on #1719, the last 5 commits are new.

Drafted as it still needs a grafana dashboard update.

### CODE REVIEW

**Comment by niklaslong** [comment]
Screenshot 2022-04-07 at 12 20 58

**Review by ljedrz — APPROVED** [review]
LGTM :+1:

**Comment by ljedrz** [comment]
~note: I don't see the grafana file update among the last 5 commits, likely needs its own final commit?~

nope, it was GitHub being buggy and showing only the last 2 commits instead of 5 (when using the commit filter)

**Comment by niklaslong** [comment]
I'll rebase once #1719 is merged.

**Pull request closed without merging**
