### PR TITLE
feat: deferred de/serialisation for transactions

### PR DESCRIPTION
**Pull request by niklaslong**
Follow up to #1356, introduces the deferred de/serialisation of unconfirmed transactions.

### CODE REVIEW

**Comment by apruden2008** [comment]
@ljedrz can you please give this a look when you get a chance?

**Comment by ljedrz** [comment]
@apruden2008 since we currently don't expect transactions to be propagated in the network, this PR is not a priority for merging right now; it's definitely desirable to have a bit later, though.

**Review by ljedrz — APPROVED** [review]
LGTM, it would be best if it was rebased and merged after https://github.com/AleoHQ/snarkOS/pull/1447.

**Comment by howardwu** [comment]
@niklaslong I think this PR is ready for rebasing, as some APIs have changed w.r.t. #1447

**Pull request closed without merging**
