### PR TITLE
fix(sync): Fix client sync RwLock deadlock and client block request stall

### LINKED ISSUE #2916: [Bug] snarkOS sometimes stops syncing
## 🐛 Bug Report

My node sometimes will stop syncing without any warning. Here's the log:

```
2023-12-12T21:34:51.848247Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795                                                                   
2023-12-12T21:34:51.849142Z TRACE snarkos_node_sync::block_sync: Prepared 0 block requests                     
2023-12-12T21:34:54.850241Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795                                                                   
2023-12-12T21:34:54.851316Z TRACE snarkos_node_sync::block_sync: Prepared 22 block requests                                                                                                                       
2023-12-12T21:34:58.103790Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795                                                                   
2023-12-12T21:34:58.104740Z TRACE snarkos_node_sync::block_sync: Prepared 9 block requests         
2023-12-12T21:35:01.211026Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795
2023-12-12T21:35:01.211727Z TRACE snarkos_node_sync::block_sync: Prepared 13 block requests
2023-12-12T21:35:04.357960Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795
2023-12-12T21:35:04.358547Z TRACE snarkos_node_sync::block_sync: Prepared 5 block requests
2023-12-12T21:35:07.416330Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795
2023-12-12T21:35:07.416927Z TRACE snarkos_node_sync::block_sync: Prepared 18 block requests
2023-12-12T21:35:10.621421Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 925872, canon_height = 925795
2023-12-12T21:35:10.622391Z TRACE snarkos_node_sync::block_sync: Prepared 0 block requests
2023-12-12T21:35:13.128856Z DEBUG snarkos_node_router::heartbeat: Connected to 80 peers [...]
```

Unfortunately I've just removed some additional debug logs when investigating another potential issue so I'm not sure why the node stopped to process the block responses (assuming I do have received responses here).

Note that my node is connected to 80+ other nodes and if you look carefully the block sync interval is also adjusted, so officially it's out of specs right now (cli doesn't have options for specifying max peers).

Also sadly I can't use verbosity 5 and run the node until it happens again, it's way too noisy as I have too many connected nodes here, and reproducing this might take weeks.

BTW, when I was investigating "another potential issue" I found that the sync module sometimes would leave some stray block responses in the `responses` map in `BlockSync` struct in unknown circumstances. Not sure if it's related.

## Steps to Reproduce

Not exactly sure.

## Expected Behavior

The node should sync.

## Your Environment

- snarkOS Version: 4896a1200a4605d1de6fe6cb53e1efa9ccdb6152, but I believe I've seen this behavior well before this
- 
-

### LINKED ISSUE #2978: [Bug] Sync module has racing condition on some checks
## 🐛 Bug Report

The log (with reduced sync and heartbeat intervals):

```

2024-01-08T17:30:46.360076Z DEBUG snarkos_node_router::handshake: Connecting to 35.224.50.150:4133...
2024-01-08T17:30:46.498847Z  INFO snarkos_node_router::handshake: Connected to '35.224.50.150:4133'
2024-01-08T17:30:47.318394Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127749
2024-01-08T17:30:47.320073Z TRACE snarkos_node_sync::block_sync: Prepared 50 block requests
2024-01-08T17:30:53.013389Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127750
2024-01-08T17:30:53.015090Z TRACE snarkos_node_sync::block_sync: Prepared 1 block requests
2024-01-08T17:30:53.023921Z  INFO snarkos_node_bft_ledger_service::ledger:

Advanced to block 1127750 at round 2352850 - ab1l7l6x3jej9fzdqwecs96lp6m9sqpverqg4uwkpmgha2r0fjeeszs40f346

2024-01-08T17:30:58.089332Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127751
2024-01-08T17:30:58.091648Z TRACE snarkos_node_sync::block_sync: Prepared 1 block requests
2024-01-08T17:30:58.091869Z DEBUG snarkos_node_router::heartbeat: Connected to 1 peer: [35.224.50.150:4133]
2024-01-08T17:30:58.099467Z  INFO snarkos_node_bft_ledger_service::ledger:

Advanced to block 1127751 at round 2352852 - ab1mq3v8ypsrfepjh35t0thje9l9mv3djm5ls8negr589mkkpw5mqrsxe73qs

2024-01-08T17:31:01.103764Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127751
2024-01-08T17:31:01.104716Z TRACE snarkos_node_sync::block_sync: Prepared 1 block requests
2024-01-08T17:31:04.119788Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127751
2024-01-08T17:31:04.120722Z TRACE snarkos_node_sync::block_sync: Prepared 47 block requests
2024-01-08T17:31:07.695287Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127751
2024-01-08T17:31:07.696388Z TRACE snarkos_node_sync::block_sync: Prepared 0 block requests
2024-01-08T17:31:08.092324Z DEBUG snarkos_node_router::heartbeat: Connected to 1 peer: [35.224.50.150:4133]
2024-01-08T17:31:10.698087Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127751
2024-01-08T17:31:10.699059Z TRACE snarkos_node_sync::block_sync: Prepared 1 block requests
2024-01-08T17:31:14.683545Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127752
2024-01-08T17:31:14.685213Z TRACE snarkos_node_sync::block_sync: Prepared 2 block requests
2024-01-08T17:31:14.705284Z  INFO snarkos_node_bft_ledger_service::ledger:

Advanced to block 1127752 at round 2352854 - ab18upqaram79ewsruj2rgce0v3gp9kvmxcvv9atvy9a5vrquas9yxqgpguut

2024-01-08T17:31:19.283766Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 1138544, canon_height = 1127753
2024-01-08T17:31:19.284845Z TRACE snarkos_node_sync::block_sync: Prepared 1 block requests
2024-01-08T17:31:19.284983Z DEBUG snarkos_node_router::heartbeat: Connected to 1 peer: [35.224.50.150:4133]
2024-01-08T17:31:19.294601Z  INFO snarkos_node_bft_ledger_service::ledger:
Advanced to block 1127753 at round 2352856 - ab1pjjhfy26khq6rlywvvknfxy4d4x3c7r6kckats8q7nw0zvhjpq9s8qqhs7

2024-01-08T17:31:24.324350Z TRACE snarkos_node_sync::block_sync: Updating is_block_synced: greatest_peer_height = 0, canon_height = 1127754
2024-01-08T17:31:24.324450Z TRACE snarkos_node_sync::block_sync: Prepared 0 block requests
2024-01-08T17:31:24.333724Z  INFO snarkos_node_bft_ledger_service::ledger:

Advanced to block 1127754 at round 2352858 - ab1gt0msxch423xswydku6axhx4dx8knem5jdlf4pkw20wa5gf5t5zsye4j8g

2024-01-08T17:31:24.717928Z TRACE snarkos_node_sync::block_sync: Block sync is removing all block requests to peer 35.224.50.150:4133...
2024-01-08T17:31:24.718075Z  WARN snarkos_node::client::router: The sync pool did not request block 1127755
2024-01-08T17:31:24.718286Z  WARN snarkos_node::client::router: Disconnecting from '35.224.50.150:4133' - Peer '35.224.50.150:4133' sent an invalid block response
2024-01-08T17:31:24.718746Z TRACE snarkos_node_sync::block_sync: Block sync is removing all block requests to peer 35.224.50.150:4133...
```

I believe this should not happen even with reduced intervals as advancing blocks is pretty slow right now.

## Steps to Reproduce

Try to sync. Eventually it will happen. Best observed when there is only 1 connection.

## Expected Behavior

This should not happen.

## Your Environment

- testnet3
- 
-

### PR DESCRIPTION
**Pull request by Meshiest**
## Motivation

We have observed two different kinds of stalls while we conduct client-sync acceptance tests on canarynet. These issues are most noticeable and reproducible when block response processing takes a sufficient amount of time. These two issues can be classified as follows:

- process.write deadlock during block response
- block request starvation

### Background

There are two places during block sync where `process` is write locked ([`atomic_speculate`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/finalize.rs#L268) and [`atomic_finalize`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/finalize.rs#L573)), and two places where `process` is read locked ([`check_execution_internal`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/verify.rs#L307) and [`check_fee_internal`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/verify.rs#L338)). Both of the write locks occur in the same [`try_advancing_with_block_responses`](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L338-L359) in series in [`check_next_block`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/ledger/src/check_next_block.rs#L73) and [`add_next_block`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/mod.rs#L424).

This code is primarily run during a [`BlockResponse`](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/router/src/inbound.rs#L134) message that invokes [`advance_with_sync_blocks`](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/src/client/router.rs#L218-L227). It has a [guard before calling `try_advancing_with_block_responses`](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L325-L328) to ensure no block responses are trying to write in parallel (thus creating a deadlock).

We have observed that [this particular area in `atomic_post_ratify`](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/finalize.rs#L1238-L1241) can take quite a while (more than 5 seconds) while [holding the write lock](https://github.com/AleoNet/snarkVM/blob/mainnet-staging/synthesizer/src/vm/finalize.rs#L268) in `atomic_speculate`.

Client nodes have [this loop that kicks off the block requests](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/src/client/mod.rs#L168-L179) firing every 5 seconds that coincidentally also calls [`try_advancing_with_block_responses` but without guards](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L233-L240) to check if another try_advance is running from the aforementioned block responses.

If an `atomic_speculate` took long enough and continued into the 5 second client sync loop while no block requests were active, this issue would occur and result in a permanent stall without block advancement until the node is restarted.

### Fix

We added a guard to the `try_block_sync` and stopped running into this issue

### Background

In order for block requests to be created for a given height it must meet the following criteria (outlined in [`check_block_request`](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L538-L555)):
- Height must be greater than current canon height
- A request for this height must not already exist
- A response for this height must not already exist
- A request timestamp for this height must not already exist

Existing block requests, responses, and timestamps are removed given the following (issue relevant) criteria:
- A peer disconnects and [all associated block requests and timestamps are removed](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L638-L657)
- The [next block is advancing](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L339) and [the request is "complete"](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L605) by having an empty peer ips set but not if the request is missing, [even though peer requests can be removed when the peer ips are empty](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L647-L650)
- A [peer provides a block response](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L507-L533), which removes the peer ip from the request set without removing the request.
- A [request is timed out or for a block that has been added already](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L661-L704)

If the last peer for a block request disconnects and the [block request and timestamp is removed](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L647-L653), a block response will be left in a cycle where [new requests will not be created](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L548) and [the request will not be considered complete](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L605) for continuing block advancement. This condition results in a permanent stall without block advancement until the node is restarted.

If that alone is fixed, the node will still reach a state where [request timestamps are retained until timeout](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L684-L685) as an "incomplete request" would be one where the request's peer set exists and is not empty OR one where the peer set has been removed (technically empty and not incomplete). This condition results in repeated temporary stalls until the block request is timed out as [new block requests will not be created until the `request_timestamp` is timed out](https://github.com/AleoNet/snarkOS/blob/mainnet-staging/node/sync/src/block_sync.rs#L552)

### Fix

By flipping the `unwrap_or(false)` to `unwrap_or(true)` in `requests.get(height).map(|(_, _, peer_ips)| peer_ips.is_empty()).unwrap_or(false)`, we are treating the empty `peer_ips` set as a "completed" peer request and allowing both block advancement to continue and real incomplete blocks to be removed

## Test Plan

We have successfully deployed this and synced 7 clients (1 alone on a 3995WX, 2 on a shared 2xEPYC 9354, and 4 on standalone GCP 16vCPU 64GB `e2-standard-16` instances) through canary blocks 28,000 through 35,000 that were particularly stressful on clients.

Last week we ran a 100 client sync test with constant stalling as low as block 8000
image

Today we have two pairs of 100 clients syncing the troublesome blocks right now
image

The stall in this screenshot is discovering and fixing the temporary stall issue
image

Note that the servers running these clients are still properly syncing without stalls despite both being under spec and running 10 clients each...

## Related PRs

- Helps with #3063
- Fixes #2916 
- Fixes #2978

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
LGTM :ok_hand:.

There are likely other scenarios where we are triggering some of the logic too eagerly and should utilize `try_lock` in order to avoid calling it in rapid succession, though this case was probably the most problematic due to the dual guard setup.

**Review by niklaslong — APPROVED** [review]

**Review by raychu86 — APPROVED** [review]
LGTM.

We originally only had a `advance_with_sync_blocks_lock` in the `advance_with_sync_blocks`, but this should also be done on the periodic `try_block_sync`. Great catch.

**Comment by HarukaMa** [comment]
Can confirm as well that this fixes deadlock and stalls, great work!

**Review by joske — APPROVED** [review]

**Comment by apruden2008** [comment]
Thanks @Meshiest @damons for the great work here. 

@zosorock this is good to merge pending CI passing

**Pull request merged**
