### PR TITLE
Merkle tree parallelize integration + upgrade to snarkVM 0.4.0

### PR DESCRIPTION
**Pull request by Protryon**
This PR integrated snarkVM 0.4.0 which adds merkle tree parallel building and partial parallel rebuilding.

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
LGTM :+1:

**Comment by ljedrz** [comment]
Since this PR changes `Cargo.lock`, maybe you could also run `cargo update` on this branch so we can both update `snarkVM` and the pending dependabot items?

**Review by howardwu — APPROVED** [review]

**Comment by howardwu** [comment]
LGTM

**Comment by howardwu** [comment]
Updated Cargo.lock following @ljedrz 's suggestion

**Comment by ljedrz** [comment]
Cc https://github.com/AleoHQ/snarkOS/issues/775.

**Pull request merged**
