### PR TITLE
(hot)fixed windows compile

### PR DESCRIPTION
**Pull request by fmu1337**
## Motivation

Help out community, meh

## Test Plan

I'm just got a lot of errors, cause termion isn't support windows OS.

Founded resolve there:
https://github.com/Byron/dua-cli/issues/2#issuecomment-630301477

## Related PRs

(Link your related PRs here)

### CODE REVIEW

**Comment by ljedrz** [comment]
Thanks for the PR, @fmu1337! We actually shouldn't be using `termion` at all, as the `crossterm` backend is used instead. I tried tinkering with it for a short while, but for some reason it persists in `Cargo.lock` :thinking:.

**Comment by fmu1337** [comment]
> Thanks for the PR, @fmu1337! We actually shouldn't be using `termion` at all, as the `crossterm` backend is used instead. I tried tinkering with it for a short while, but for some reason it persists in `Cargo.lock` 🤔.

This one?
https://github.com/AleoHQ/snarkOS/blob/bc518c3e29faae7323cef516e1e0242cc8ca6c09/Cargo.lock#L2471

Also I found 

.cargo\registry\src\github.com-1ecc6299db9ec823\tui-0.16.0\Cargo.toml 
```
145. [dependencies.termion]
146. version = "1.5"
147. optional = true
```

**Comment by ljedrz** [comment]
> optional = true

Yeah, this is exactly why I'm surprised to see it in the lockfile; it's neither a default feature nor do we enable it manually.

**Comment by ljedrz** [comment]
Upon further digging, I found an issue in `tui` that might be affecting this and filed https://github.com/fdehau/tui-rs/pull/571.

**Comment by howardwu** [comment]
Closing in favor of #1483

**Pull request closed without merging**
