### PR TITLE
Revert "Avoid unnecessary calculations in propose_batch"

### PR DESCRIPTION
**Pull request by zosorock**
Reverts AleoNet/snarkOS#3265

Sorry about that @elderhammer - that PR was accidentally merged into the wrong branch. It should have targeted `mainnet-staging` so that we can test before merging into `mainnet`.

Thank you for your contribution!

### CODE REVIEW

**Comment by elderhammer** [comment]
> Reverts #3265
> 
> Sorry about that @elderhammer - that PR was accidentally merged into the wrong branch. It should have targeted `mainnet-staging` so that we can test before merging into `mainnet`.
> 
> Thank you for your contribution!

Should I resubmit a PR to address this issue?

**Review by Meshiest — APPROVED** [review]
LGTM for revert. Probably need to be extra careful about Mainnet merges in the future as they'll trigger rebuilds for the whole network lol

**Comment by apruden2008** [comment]
LGTM

**Review by apruden2008 — COMMENTED** [review]
LGTM

**Review by apruden2008 — APPROVED** [review]

**Comment by zosorock** [comment]
> Should I resubmit a PR to address this issue?

yes please @elderhammer - just target the `mainnet-staging` branch and we can merge it in. Thank you!

**Comment by elderhammer** [comment]
> > Should I resubmit a PR to address this issue?
> 
> yes please @elderhammer - just target the `mainnet-staging` branch and we can merge it in. Thank you!

Done. https://github.com/AleoNet/snarkOS/pull/3275

**Pull request merged**
