### PR TITLE
Improve resource management

### PR DESCRIPTION
**Pull request by ljedrz**
This PR improves the resource accounting setup, fixing a connection-related memleak and gracefully shutting down the ledger reader thread upon shutdown.

It also isolates a `snarkos-utils` crate which can host code applicable to any workspace member which might not depend on `snarkos` (in this case `storage`, but also e.g. the [network crawler](https://github.com/AleoHQ/snarkOS/pull/1533) node impl).

### CODE REVIEW

**Comment by ljedrz** [comment]
In a future PR I'd like to extend this setup with named resources, which will allow us to shut the node down more quickly. I've already started prototyping it, but wouldn't want to enlarge this PR any further.

**Review by niklaslong — APPROVED** [review]
Nice improvement and LGTM 👍

**Comment by ljedrz** [comment]
Rebased.

**Comment by ljedrz** [comment]
Superseded by https://github.com/AleoHQ/snarkOS/pull/1639.

**Pull request closed without merging**
