### PR TITLE
Mainnet Beta release v0.1.0

### PR DESCRIPTION
**Pull request by zosorock**
## Motivation
Updating Mainnet Beta genesis block for release `v0.1.0` and adding Mainnet bootstrap peers.

## Related PRs
https://github.com/AleoNet/snarkVM/pull/2542

### CODE REVIEW

**Review by Meshiest — DISMISSED** [review]
LGTM (once cargo.toml is updated)

**Comment by zkxuerb** [comment]
Do we need to bump Message and Event versions @zosorock  ?

**Comment by raychu86** [comment]
There's no need to bump Message and Event versions because there is no current network running.

**Review by zkxuerb — DISMISSED** [review]
LGTM (once snarkvm rev is updated)

**Review by evanmarshall — DISMISSED** [review]

**Review by zkxuerb — DISMISSED** [review]

**Review by snarkworld — DISMISSED** [review]

**Review by snarkworld — APPROVED** [review]

**Pull request merged**
