### PR TITLE
Cleanup metrics

### PR DESCRIPTION
**Pull request by Protryon**
Creates a wrapped channel for more reliable metrics reporting.

### CODE REVIEW

**Comment by niklaslong** [comment]
Running this locally, `inbound_network_messages` is showing negative values. Other queue metrics are flatlining as well.

**Comment by Protryon** [comment]
> Running this locally, `inbound_network_messages` is showing negative values. Other queue metrics are flatlining as well.

I fixed the issue with it going negative.

Flatlining to zero is the expected behavior for a properly functioning message queue? Unless there is a backlog.

**Comment by niklaslong** [comment]
> Flatlining to zero is the expected behavior for a properly functioning message queue?

Indeed, though I never saw it rise despite seeing that whilst running a node on `staging` just prior with the same configuration. I may be wrong but wanted to raise the observation.

**Review by niklaslong — APPROVED** [review]

**Comment by Protryon** [comment]
> > Flatlining to zero is the expected behavior for a properly functioning message queue?
> 
> Indeed, though I never saw it rise despite seeing that whilst running a node on `staging` just prior with the same configuration. I may be wrong but wanted to raise the observation.

I was able to see storage climb during an expensive storage action series.

**Pull request merged**
