### PR TITLE
Improve block processing time metrics

### PR DESCRIPTION
**Pull request by niklaslong**
Adds some detail to the block processing metrics by also tracking the block verification and commit time.

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
LGTM :+1:

**Comment by ljedrz** [comment]
While running this branch and checking the metrics, I thought that perhaps we could improve the name of the `block_processing_time` one now, in order not to confuse the users? Alternatively, we could skip its accounting if the node is currently syncing; I'm just wondering if that metric isn't misleading now :thinking:.

**Comment by niklaslong** [comment]
I'd be happy to remove it, though do we want to keep it as is as a reference to improve the performance of the costly processing? Not tracking it during sync means we won't see many values as most nodes are syncing until they reach the canon tip.

**Comment by ljedrz** [comment]
I'm ok with keeping it, just wondering if there's some better name for it, perhaps `inbound_block_processing_time` (verbose) or perhaps extending the RPC description would help here.

**Comment by niklaslong** [comment]
I've made the clarification in the docs for now. It might soon be worth moving some of the `misc` metrics to a `block` struct in a follow-up, since most of the misc metrics are currently block related (with the exception of the rpc call count).

**Pull request merged**
