### PR TITLE
Remove the legacy storage impl

### LINKED ISSUE #1094: Sqlite Migration Tracking Issue
See #1078 for implementation of sqlite backend & migration.

- [x] Merge sqlite backend (#1078)
- [x] Release new version of snarkOS, get users to update
- [ ] With critical mass, remove rocksdb implementation, dependency, migration script, and possibly storage validator.

### PR DESCRIPTION
**Pull request by ljedrz**
This PR removes the `rocksdb` storage backend, the remaining bits of the now-obsolete in-memory storage implementation and the legacy storage validator.

Closes https://github.com/AleoHQ/snarkOS/issues/1094.

### CODE REVIEW

**Review by niklaslong — APPROVED** [review]
lgtm (will need a rebase) 👍

**Comment by Protryon** [comment]
I think we should wait for at least one more release cycle to ensure no one else has a rocksdb instance still running, unless we have clear numbers saying most people have upgraded.

**Comment by ljedrz** [comment]
Converted the PR to a draft until we decide it's time to move forward with it.

**Comment by ljedrz** [comment]
Rebased.

**Comment by ljedrz** [comment]
Closing the PR as it's no longer applicable to testnet2.

**Pull request closed without merging**
