### PR TITLE
Use a custom function to deserialize the IndexMaps in BlockLocators

### PR DESCRIPTION
**Pull request by ljedrz**
A follow-up to https://github.com/AleoHQ/snarkOS/pull/2456.

This was found via simple fuzzing; it appears that `with_limit` doesn't fully guard us against overallocations, so introduce and use a custom method to deserialize the `IndexMap`s in `BlockLocators`.

Filing as a draft, as I'm not sure if we don't want to approach this some other way (e.g. restricting the number of entries etc.).

### CODE REVIEW

**Comment by howardwu** [comment]
What's the perf hit of using this custom deserializer?

Also, shouldn't this be brought up to the `indexmap` crate for fixing?

**Comment by ljedrz** [comment]
> What's the perf hit of using this custom deserializer?

As far as I'm aware, there shouldn't be any; also, this implementation is basically the same as the one in `IndexMap`, just doesn't pre-allocate.

> shouldn't this be brought up to the indexmap crate for fixing?

AFAICT this would be a `serde` issue. Actually, I just looked at it and can see that there have been some related changes recently, so perhaps it would no longer be needed (i.e. it should be checked again).

Ultimately, though, it would be best to just use the `impl<N: Network> FromBytes for BlockLocators<N>` that was merged into the `narwhal` branch today, in order to have full control over deserialization. If that is the intent, this PR can be closed.

**Comment by howardwu** [comment]
Let's switch out all of the Router messages to `To/FromBytes` just like the Gateway events.

**Comment by ljedrz** [comment]
Superseded by https://github.com/AleoHQ/snarkOS/pull/2731.

**Pull request closed without merging**
