### PR TITLE
Update snarkVM to 0.7.6

### PR DESCRIPTION
**Pull request by ljedrz**
Fixes https://github.com/AleoHQ/snarkOS/issues/1004.

### CODE REVIEW

**Comment by ljedrz** [comment]
```
ssh: connect to host github.com port 22: Connection timed out
```
Seems spurious, will restart once other jobs are complete.

**Comment by ljedrz** [comment]
Actually, it seems that some of the failures are legitimate and that the test data will need to be re-generated. I'm on it.

**Review by Protryon — APPROVED** [review]

**Comment by ljedrz** [comment]
I updated the test blobs, but I'm still trying to track the transaction RPC.

**Comment by ljedrz** [comment]
@howardwu all green now; leaving this up to you in case there's any other adjustment needed - otherwise it should be good to go for the next release.

**Review by howardwu — APPROVED** [review]

**Pull request merged**
