### PR TITLE
Update one last license

### LINKED ISSUE #2250: [Bug] failed to run custom build command for `snarkos v2.0.2
## 🐛 Bug Report

when I run "./build_ubuntu.sh",then it show
image

## Your Environment

snarkOS v2.0.2
rustc 1.67.1 (d5a82bbd2 2023-02-07)
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by ljedrz**
Fixes https://github.com/AleoHQ/snarkOS/issues/2250.

### CODE REVIEW

**Review by niklaslong — APPROVED** [review]

**Comment by ljedrz** [comment]
Merging this one ahead of time to avoid compilation issues for the users.

**Comment by sajshuai** [comment]
image
it caused another problem

**Comment by ljedrz** [comment]
It didn't, at most it uncovered it; how are you building? I'm able to run `cargo build --release` without any issues.

**Comment by lambry03** [comment]
> image
> 
> it caused another problem

i got the same problem. Does it has to do with compiling with only 8 cpu cores

**Comment by sajshuai** [comment]
`cargo build --release` is ok.
It's a problem with 'cargo install --path .' when compile `snarkos-node-ledger

**Comment by ljedrz** [comment]
> Does it has to do with compiling with only 8 cpu cores

No, it's unrelated; I think it's because the snarkVM dependency had its version bumped, and while it was (semver-wise) a bugfix release, it was breaking, which means that you'd need to be careful not to auto-update it in your local repo; snarkVM 0.9.11 does work.

FWIW, a related PR is already pending: https://github.com/AleoHQ/snarkOS/pull/2238.

**Pull request merged**
