### PR TITLE
Fix/rpc request serde

### LINKED ISSUE #1369: [Bug] Numeric `id` not supported anymore in JSON RPC call
## 🐛 Bug Report

JSON RPC does not accept a numeric `id` anymore and responds with `Couldn't parse the RPC body`. When `id` is given as a String or Null, the API call works. This behavior is new and was apparently introduced in a change within the past 12 hours.

## Steps to Reproduce

1. `curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"latestblockheight","params":[],"id":1}' localhost:3032`
Output: `{"jsonrpc":"2.0","error":{"code":-32700,"message":"Couldn't parse the RPC body"},"id":null}`

2. `curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"latestblockheight","params":[],"id":"1"}' localhost:3032`
Output: `{"jsonrpc":"2.0","result":6864,"id":"1"}`

## Expected Behavior

Support `id` as String, Number and Null, as in the JSON RPC specs

## Your Environment

snarkOS: 2.0.0 (c762a1d453b98e2e34208b16a3405e6a9e63c33d)
Rust: 1.56.1
OS: Ubuntu Linux 20.04

### PR DESCRIPTION
**Pull request by whalelephant**
## Motivation

Closes #1369 without introducing new dependencies with jsonrpc-* crates.

There is an issue with parsing numerical value with json rpc id field. The work around implemented is to first parse into `serde_json::Value` as suggested [here](https://github.com/serde-rs/serde/issues/1413).

Another [PR](https://github.com/DoumanAsh/json-rpc-types/pull/2) to the temp dependency json-rpc-type fixes the issue of how `serde_json::Value` string deserialization requires escaping and cannot therefore be cast to a borrowed str type. 

## Test Plan

```
 curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"latestblockheight","params":[],"id":"1"}' localhost:3032
 
 curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"latestblockheight","params":[],"id":1}' localhost:3032
```

## Related PRs

 #1496 
#1537

### CODE REVIEW

**Comment by ljedrz** [comment]
The CI doesn't want to start; I'll try reopening, it sometimes helps.

**Comment by ljedrz** [comment]
Did it get stuck again? Let me retry.

**Review by ljedrz — APPROVED** [review]
LGTM :+1:

**Review by raychu86 — APPROVED** [review]

**Review by raychu86 — APPROVED** [review]
LGTM

**Pull request merged**
