### PR TITLE
Re-enable incremental compilation

### LINKED ISSUE #1010: Re-enable incremental compilation
Rust `1.54.0` [re-enables incremental compilation by default](https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#incremental-compilation-is-re-enabled-by-default) following issues reported in the `1.52.0` and it being disabled in `1.52.1`. We may want to wait until the next release before re-enabling it ourselves, to be extra safe.

### PR DESCRIPTION
**Pull request by niklaslong**
Rust `1.55` has been released, re-enables incremental compilation as detailed in #1010.

### CODE REVIEW

**Comment by niklaslong** [comment]
Looks like there's a ci glitch 👀

**Comment by ljedrz** [comment]
> Looks like there's a ci glitch :eyes:

Shouldn't this branch be against `staging`, though :detective:?

**Comment by niklaslong** [comment]
good catch 👍

**Review by ljedrz — APPROVED** [review]
There still seem to be some unresolved related issues, but they don't appear to be severe/probable enough to keep this feature disabled; I'm ok with this :+1:

**Pull request merged**
