### PR TITLE
Fix(tcp): avoid self-connects

### PR DESCRIPTION
**Pull request by niklaslong**
Should fix the self-connect issue observed on testnet whilst still allowing for testing on loopback.

### CODE REVIEW

**Review by ljedrz — COMMENTED** [review]
This should fix the issue, but it would also cause all connections coming from own IP address to be rejected; are `--dev` nodes excluded from this logic?

**Comment by niklaslong** [comment]
Only if these aren't loopback addresses. We likely wouldn't want to bind to an external IP when running with `--dev`?

**Review by ljedrz — APPROVED** [review]

**Comment by ljedrz** [comment]
I also wonder if there are users who start multiple nodes on a single machines and intend them all to be able to connect to one another without relying on local IPs. It's probably a niche use case, but it's possible.

In any case, the best solution would be to use non-IP identifiers.

**Review by Sharpshop — APPROVED** [review]

**Review by howardwu — APPROVED** [review]

**Comment by howardwu** [comment]
LGTM

**Pull request merged**
