### PR TITLE
[Optimize] Further blocking tweaks

### PR DESCRIPTION
**Pull request by ljedrz**
This PR moves 2 additional potentially blocking operations into blocking tasks; they were found to be significant using `tokio-console`, which was also used to double-check that these changes decrease the `Busy` time of the associated tasks.

### CODE REVIEW

**Review by joske — APPROVED** [review]

**Comment by howardwu** [comment]
@vicsn @onetrickwolf @iamalwaysuncomfortable We will need to validate this branch with at least 12 hours of burn-in prior to approvals.

**Comment by ljedrz** [comment]
I'll fix the `clippy` issue shortly; as far as I can tell, it will not affect performance.

**Comment by raychu86** [comment]
Double-clicking on this. @vicsn @onetrickwolf @iamalwaysuncomfortable Did we get a chance to burn-in test this change?

**Comment by howardwu** [comment]
@vicsn @onetrickwolf @iamalwaysuncomfortable When will this be addressed?

**Comment by vicsn** [comment]
Starting to test this now

**Review by howardwu — APPROVED** [review]
LGTM, adding this in for additional burn-in testing overnight.

**Comment by vicsn** [comment]
> Starting to test this now

Looks good. Ran for 12+ hours with 1.6 TPS and 3 seconds/block.

**Pull request merged**
