### PR TITLE
Update testnet2_ubuntu.sh

### PR DESCRIPTION
**Pull request by Pa1amar**
## Motivation

(Write your motivation here)

## Test Plan

(Write your test plan here)

## Related PRs

(Link your related PRs here)

### CODE REVIEW

**Comment by ljedrz** [comment]
Some description would be in order; what's the motivation for this change?

**Comment by Pa1amar** [comment]
I get error

error: failed to compile 'snarkos v 2.0.0 (/root/snarkOS)', intermediate artifacts can be found at '/root/snarkOS/target'
failed to select a version for the requirenent 'futures = "^0.3.18"

**Comment by alar0n** [comment]
I resolved this problem:
nano ./Cargo.toml

and change position
futures = { version = "0.3.18", features = ["thread-pool"]}

to
futures = { version = "0.3.17", features = ["thread-pool"]}
 
i dont know why in my Cargo.toml existed 0.3.18...
i taked distrib from git by:
git clone https://github.com/AleoHQ/snarkOS.git --depth 1

**Comment by ljedrz** [comment]
> I get error
> error: failed to compile 'snarkos v 2.0.0 (/root/snarkOS)', intermediate artifacts can be found at '/root/snarkOS/target'
> failed to select a version for the requirenent 'futures = "^0.3.18"

This was fixed with https://github.com/AleoHQ/snarkOS/pull/1440, just update your `testnet2` branch. Closing the PR, as it won't be an issue anymore.

**Pull request closed without merging**
