### PR TITLE
Tracking: documentation updates

### PR DESCRIPTION
**Pull request by collinc97**
This PR can be merged immediately or modified if more endpoint changes occur.
- [x]  add documentation for get node status endpoint

### CODE REVIEW

**Comment by howardwu** [comment]
@collinc97 

- In #1321:
    - [x] Adds `number_of_connected_sync_nodes` to `getnodestate` RPC endpoint

**Comment by howardwu** [comment]
Changes from snarkVM (updating iteratively here):

- `Transition` has removed `ciphertext_ids`
- `Record` has removed `serial_number_nonce` and `commitment_randomness`
- `Record` has added `randomizer` and `record_view_key`

**Comment by howardwu** [comment]
- #1363

**Comment by collinc97** [comment]
- [x] fix `getciphertext` input and output
- [x] update block header metadata with cumulative weight, move posw nonce out of metadata
- [x] update all examples

**Comment by collinc97** [comment]
- [x] create `getblocktemplate`
- [x] fix `getmemorypool`

**Comment by collinc97** [comment]
- [x] update json rpc `"id":1` -> `"id":"1"`

**Review by howardwu — APPROVED** [review]

**Pull request merged**
