### PR TITLE
Add a connection memleak test

### PR DESCRIPTION
**Pull request by ljedrz**
It doesn't seem like we have any leaks there at the moment, but it would be a good idea to preserve this test to ensure this with any future changes to peering.

### CODE REVIEW

**Comment by ljedrz** [comment]
Ah yeah, the test points to in-memory storage; should I make the (snarkOS) ledger more generic, or disable the test more thoroughly?

**Comment by Zerohedge2020** [comment]
> Ah yeah, the test points to in-memory storage; should I make the (snarkOS) ledger more generic, or disable the test more thoroughly?

how thats gonna build up the generic storage though?

**Comment by ljedrz** [comment]
> how thats gonna build up the generic storage though?

It's not for building generic storage; a single type of storage would still be used in the test.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable; an up-to-date rendition of this test will be filed soon.

**Pull request closed without merging**
