### PR TITLE
Don't deserialize values in DataMap::contains_key

### PR DESCRIPTION
**Pull request by ljedrz**
This PR is a more conservative subset of https://github.com/AleoHQ/snarkOS/pull/1548, which introduces `DataMap::get_raw` as a private method outside of the `Map` trait and only uses it internally in `DataMap::{contains_key, get}`.

While it doesn't resolve the slowness of `LedgerState::get_block_height`, it speeds up all operations that only require a key lookup (i.e. without the value):
```
blocks_lookup_by_height time:   [542.84 ns 545.86 ns 550.06 ns]                                     
                        change: [-25.741% -25.159% -24.648%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe

blocks_lookup_by_hash   time:   [928.80 ns 932.03 ns 936.64 ns]                                   
                        change: [-99.998% -99.998% -99.998%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe

txs_lookup_by_id        time:   [835.93 ns 837.28 ns 838.76 ns]                              
                        change: [-43.962% -43.622% -43.302%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe

txs_lookup_by_commitment                                                                             
                        time:   [803.40 ns 805.60 ns 807.79 ns]
                        change: [-28.090% -27.790% -27.490%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

txs_lookup_by_serial_number                                                                             
                        time:   [776.41 ns 778.45 ns 780.65 ns]
                        change: [-18.588% -18.194% -17.781%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe
```

### CODE REVIEW

**Review by jules — APPROVED** [review]
LGTM!

**Review by niklaslong — APPROVED** [review]

**Comment by ljedrz** [comment]
Rebased.

**Comment by ljedrz** [comment]
@howardwu this PR is safe to merge; it changes nothing besides actually ignoring the value in key-only lookups (which is already being ignored, but fully deserialized).

**Review by howardwu — APPROVED** [review]

**Comment by howardwu** [comment]
LGTM, nice work!

**Pull request merged**
