### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by Protryon**
This PR:
* Moves codecoverage from CircleCI to GitHub Actions (so that we can use Leo's working setup).
* Uses standard nightly fmt.

### CODE REVIEW

**Comment by ljedrz** [comment]
Canceled the workflow due to the `Code Coverage`'s `Test` step had already taken over 5 hours.

**Comment by ljedrz** [comment]
The hung tests seem to have been caused by
```
protected_rpc_tests::test_rpc_create_raw_transaction
protected_rpc_tests::test_rpc_create_transaction
```
which didn't use to be flaky; in any case, we need to add a timeout so that we don't burn through too much of CI time.

**Comment by ljedrz** [comment]
related: I'm also experiencing hangs with `parameters::tests::verify_header` locally

**Comment by Protryon** [comment]
> related: I'm also experiencing hangs with `parameters::tests::verify_header` locally

Might be trying to pull parameters on each CI node and wasting a ton of time pulling a GB over a presumably throttled connection.

**Comment by Protryon** [comment]
Stale

**Pull request closed without merging**
