### PR TITLE
Fix path to config in the banner

### PR DESCRIPTION
**Pull request by unordered-set**
## Motivation

When I originally saw the banner, it was misleading, and I've updated the wrong config file.

## Test Plan

This is just a string change, so I've checked that it is still building.

## Related PRs

Well, actually I did some extra things:
1) added some constants for the config file name
2) added more constants about config overwriting behaviour

but overall it looked pretty ugly and probably not worth it. Please, let me know if you want me to update the pull request with that versions.

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
Good catch, thanks!

**Comment by ljedrz** [comment]
Hmm, why isn't the CI status being read? I'll reopen the PR, hopefully it'll get unstuck.

**Comment by unordered-set** [comment]
I am trying to reopen it again

**Comment by unordered-set** [comment]
@ljedrz, do you mind starting that manual checks please?

**Pull request merged**
