### PR TITLE
Fix(tcp): don't attempt to auto-disconnect twice

### PR DESCRIPTION
**Pull request by niklaslong**
Just a quick fly-by noticed the other day (also changed pea2pea). PR builds on #2106, which should be merged first; only the last commit is new.

### CODE REVIEW

**Comment by niklaslong** [comment]
Looks like there's a transitory issue with CircleCi. 
Edit: seems to be fixed now.

**Comment by niklaslong** [comment]
Rebased and now includes a bump to `pea2pea`.

**Comment by niklaslong** [comment]
Now includes a further bump to `pea2pea` (https://github.com/AleoHQ/snarkOS/pull/2127).

**Review by howardwu — APPROVED** [review]
After reading #2106, I realized this is actually a 2 (or 3) line change here. LGTM

**Pull request merged**
