### PR TITLE
[Release] v3.0.0

### PR DESCRIPTION
**Pull request by raychu86**
## Motivation

This PR updates the crate versions from `v2.2.7` to `v3.0.0`.

This corresponds with the latest crates.io release - https://crates.io/crates/snarkos.

CI run is [here](https://app.circleci.com/pipelines/github/ProvableHQ/snarkOS?branch=v3.0.0-CI).

### CODE REVIEW

**Comment by zosorock** [comment]
CI failure for check-fmt is expected until the fix is merged in by @d0cd.

**Review by vicsn — DISMISSED** [review]
LGTM

**Review by evanmarshall — DISMISSED** [review]

**Review by gluax — APPROVED** [review]

**Comment by d0cd** [comment]
The fix is implemented here: https://github.com/ProvableHQ/snarkOS/pull/16

**Review by vicsn — APPROVED** [review]
@zosorock apologies for the delay, fmt fixes are in

**Pull request merged**
