### PR TITLE
Typo fix for solution_broadcast

### PR DESCRIPTION
**Pull request by xbeastx**
unconfirmed transaction -> unconfirmed solution

### CODE REVIEW

**Review by ljedrz — APPROVED** [review]
LGTM, it was probably a copy-paste mishap originally

**Comment by ljedrz** [comment]
Note that this also applies to L353; @xbeastx can you fix it there too (and squash)?

**Comment by xbeastx** [comment]
> Note that this also applies to L353; @xbeastx can you fix it there too (and squash)?

done

**Comment by ghostant-1017** [comment]
Aha, my negligence

**Review by howardwu — APPROVED** [review]

**Pull request merged**
