### PR TITLE
Update testnet2_ubuntu.sh

### PR DESCRIPTION
**Pull request by unordered-set**
Add missing dependency

## Motivation

(Write your motivation here)

## Test Plan

(Write your test plan here)

## Related PRs

(Link your related PRs here)

### CODE REVIEW

**Comment by ljedrz** [comment]
I'm not an expert on firewalls, but I'm not sure `ufw` should always be installed, as the firewall might be controlled with alternative software.

**Comment by unordered-set** [comment]
@ljedrz , at https://github.com/AleoHQ/snarkOS/blob/testnet2/testnet2_ubuntu.sh#L47 it uses `ufw`

**Comment by ljedrz** [comment]
True, but my point is that in that case we might instead want to report that it's not installed and that the user should configure a firewall using a tool of their choosing instead of potentially installing an extra one that might not match their setup.

**Comment by unordered-set** [comment]
Ah, we can use a side service to check the external availability. What do you think about it?

**Comment by raychu86** [comment]
We are trying to remove as many assumptions and dependencies as possible in the startup scripts (and will likely refactor them soon). Closing for now.

**Pull request closed without merging**
